# Generated by Django 5.2.17 on 2026-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_landlordprofile_renterprofile_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_in_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('linkedin', 'LinkedIn')], default='email', max_length=20),
        ),
    ]
