# Generated by Django 5.2.17 on 2026-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_oauth_data_user_sign_in_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
