# Generated by Django 5.2.17 on 2026-09-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_landlordprofile_paystack_subaccount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='paystack_subaccount_code',
        ),
    ]
