# Generated by Django 5.2.17 on 2026-09-15 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_landlordprofile_paystack_subaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterprofile',
            name='amenity_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('water_storage', 'Water Storage'), ('backup_power', 'Backup Power'), ('walled_gated', 'Walled Gated'), ('wifi', 'Wifi'), ('parking', 'Parking'), ('gym', 'Gym'), ('swimming_pool', 'Swimming Pool'), ('furnished', 'Furnished'), ('air_conditioning', 'Air Conditioning'), ('security', 'Security'), ('maintenance', 'Maintenance')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='preferred_payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='momo', max_length=20),
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
