# Generated by Django 5.2.17 on 2026-09-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_renterprofile_amenity_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renterprofile',
            name='school_name',
        ),
    ]
