# Generated by Django 5.2.17 on 2026-09-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_renterprofile_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
