# Generated by Django 5.2.17 on 2026-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_renterprofile_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='momo_or_bank_details',
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='momo_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
