# Generated by Django 5.2.17 on 2026-09-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_landlordprofile_momo_or_bank_details_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renterprofile',
            name='amenity_preferences',
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='amenity_preferences',
            field=models.ManyToManyField(blank=True, related_name='prefered_by_renters', to='core.amenity'),
        ),
    ]
