# Generated by Django 5.2.17 on 2026-09-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_renterprofile_amenity_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='momo_number',
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='preferred_payout_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='momo', max_length=20),
        ),
    ]
