# Generated by Django 5.2.17 on 2026-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_landlordprofile_momo_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('renter', 'Renter'), ('landlord', 'Landlord'), ('staff', 'Staff'), ('admin', 'Admin')], default=None, max_length=20, null=True),
        ),
    ]
