# Generated by Django 5.2.17 on 2026-09-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_oauth_data_user_sign_in_method'),
        ('listings', '0002_alter_listingphoto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled_no_show', 'Cancelled / No-show')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='listings.listing')),
                ('renter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='accounts.renterprofile')),
                ('staff_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewings', to='accounts.staffprofile')),
            ],
        ),
    ]
