# Generated by Django 5.2.17 on 2026-09-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewing',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='viewing',
            old_name='renter_profile',
            new_name='renter_profile_id',
        ),
        migrations.RenameField(
            model_name='viewing',
            old_name='staff_profile',
            new_name='staff_profile_id',
        ),
    ]
