# Generated by Django 5.2.17 on 2026-09-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0002_rename_listing_viewing_listing_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewing',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='viewing',
            old_name='renter_profile_id',
            new_name='renter_profile',
        ),
        migrations.RenameField(
            model_name='viewing',
            old_name='staff_profile_id',
            new_name='staff_profile',
        ),
    ]
