"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

import os

if os.name == 'nt':
    OSGEO4W = r'C:\Users\g\AppData\Local\Programs\OSGeo4W'
    os.environ['OSGEO4W_ROOT'] = OSGEO4W
    os.environ['GDAL_DATA'] = OSGEO4W + r'\share\gdal'
    os.environ['PROJ_LIB'] = OSGEO4W + r'\share\proj'
    os.environ['PATH'] = OSGEO4W + r'\bin;' + os.environ['PATH']

    GDAL_LIBRARY_PATH = OSGEO4W + r'\bin\gdal313.dll'
    GEOS_LIBRARY_PATH = OSGEO4W + r'\bin\geos_c.dll'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
# cast=bool — WITHOUT this, config('DEBUG', ...) reads .env as a plain
# TEXT string. A classic python-decouple trap: even the string "False"
# is TRUTHY in Python (any non-empty string is truthy), so DEBUG='False'
# in .env would actually evaluate to True at runtime — the opposite of
# what it says. cast=bool tells decouple to specifically recognize the
# text "True"/"False" (case-insensitively) and convert it to a REAL
# Python boolean, avoiding that trap entirely

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [h.strip() for h in v.split(',')])
# Reads a comma-separated list from .env (e.g.
# "api.paddy.com,paddy-backend.up.railway.app") and splits it into the
# list Django actually expects. Defaults to localhost-only for local
# dev. The wildcard '*' that was here before is a genuine security risk
# in production — it accepts a request claiming ANY hostname at all,
# which is the classic ingredient for Host-header-based attacks (e.g.
# a maliciously crafted password-reset link pointing at an attacker's
# domain, if any code ever builds a URL from request.get_host()).
# Real deployed domains go in .env, not hardcoded here, so they can
# differ between environments (local/staging/production) without a
# code change


# Application definition

INSTALLED_APPS = [
    'unfold',
    'anymail',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'accounts',
    'listings',
    'viewings',
    'payments',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.gis'
]

REST_FRAMEWORK = {
    # Global DRF settings — a dict DRF looks for by this exact name

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Tells DRF: on every incoming request, check for a JWT in the
    # Authorization header, and if valid, treat it as identifying the user.
    # Without this, DRF wouldn't know JWTs exist at all — SimpleJWT is
    # installed, but not yet "plugged in" as the actual auth method

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    # Applied to EVERY view by default, unless a specific view overrides
    # throttle_classes itself. AnonRateThrottle tracks by IP address (for
    # requests with no logged-in user), UserRateThrottle tracks by user
    # ID (once authenticated) — different buckets, so a logged-in user
    # isn't sharing their rate limit with anonymous traffic from the
    # same IP (e.g. behind a shared office/mobile network NAT)

    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '120/min',
        # Baseline limits for ordinary browsing/API use — generous
        # enough that a real user scrolling Discovery Hub or a
        # landlord managing listings never notices them

        'login': '5/min',
        'register': '5/min',
        # Deliberately MUCH stricter — these are the exact endpoints a
        # brute-force/credential-stuffing attack or a spam-signup bot
        # would hammer. 5/min per IP makes that kind of automated abuse
        # genuinely slow and impractical, while still being generous
        # enough that a real person mistyping their password twice
        # never gets blocked

        'sensitive': '10/min',
        # For verify-email and similar token-based flows — not as
        # tightly limited as login/register (a real user might
        # reasonably retry a broken verification link), but still
        # meaningfully throttled against abuse

        'payments': '10/min',
        # initiate_subscription proxies to Paystack's API — throttling
        # this protects against a bug or malicious client hammering
        # OUR server into hammering Paystack's, which could trigger
        # Paystack's own abuse detection against our account

        'webhook': '100/min',
        # Deliberately generous — this endpoint's real protection is the
        # HMAC signature check, not this limit. A tight limit here risks
        # dropping GENUINE Paystack webhooks if several landlords pay
        # around the same time (Paystack could send a burst of calls).
        # This exists only to cap how much CPU a flood of garbage,
        # unsigned requests can cost us, not to gate real traffic

        'viewing_request': '10/min',
        # Applied ONLY to creating a new viewing request (see
        # ViewingViewSet.get_throttles below) — this is specifically the
        # "renter spamming viewing requests" abuse case: without this, a
        # malicious or buggy client could flood a landlord's inbox with
        # bogus viewing bookings (each one triggers a real confirmation
        # email too, so this also protects against burning through email
        # sending quota). Listing/retrieving/staff actions on viewings
        # are NOT scoped this tightly — they just fall back to the
        # global 'user' rate (120/min), since browsing your own
        # viewings isn't the same abuse risk as creating new ones
    },
}


AUTH_USER_MODEL = 'accounts.User'

EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
ANYMAIL = {
    "RESEND_API_KEY": config("RESEND_API_KEY"),
    # config(...) — same decouple pattern as PAYSTACK_SECRET_KEY/
    # GOOGLE_CLIENT_ID, reads from .env correctly. The previous
    # os.environ.get(...) silently returned None here, since
    # os.environ only sees REAL OS/shell env vars — python-decouple's
    # .env-file loading is a separate mechanism that os.environ.get()
    # never taps into on its own
}
DEFAULT_FROM_EMAIL = "hello@thegeneralyst.com"
# Local dev only — prints the email content to your terminal instead of
# actually sending it. We'll swap this for a real email service
# (e.g. SendGrid, AWS SES) once we're closer to production


PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
# config(...) — same decouple pattern as GOOGLE_CLIENT_ID, reads the
# real key out of .env, never hardcoded here. This is the KEY every
# payments/views.py Paystack API call will authenticate with — same
# "one central setting" idea as EMAIL_BACKEND, just for Paystack instead

PAYSTACK_PLAN_CODE = config('PAYSTACK_PLAN_CODE', default='')
# LEGACY — superseded by the two tier-specific codes below once 3-tier
# pricing was decided. Left in place for now rather than removed, in
# case anything still references it; safe to delete once confirmed unused

PAYSTACK_AGENT_PLAN_CODE = config('PAYSTACK_AGENT_PLAN_CODE', default='')
PAYSTACK_LORD_PLAN_CODE = config('PAYSTACK_LORD_PLAN_CODE', default='')
# One real Paystack Plan per PAID tier (GHS 250/mo and GHS 1,000/mo
# respectively, created via a one-off API call, not through the
# dashboard — Paystack's dashboard doesn't have an obvious standalone
# "Plans" page, it's buried under Payment Pages). The FREE tier
# deliberately has no plan code at all — no Paystack interaction
# happens for a landlord who never exceeds their free listing


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # WhiteNoise — serves static files (CSS/JS/admin assets) directly
    # from gunicorn itself in production, compressed and cache-busted,
    # without needing a separate nginx/CDN setup just to get started.
    # MUST sit directly after SecurityMiddleware (WhiteNoise's own docs
    # specify this exact position) and BEFORE anything else — it needs
    # to intercept static file requests early, before session/auth
    # middleware does unrelated work on a request that's just asking
    # for a CSS file
    'corsheaders.middleware.CorsMiddleware',
    # Must come BEFORE CommonMiddleware (django-cors-headers' own docs
    # require this exact ordering) — CORS is fundamentally about
    # deciding whether to add specific response HEADERS
    # (Access-Control-Allow-Origin, etc.) telling the BROWSER "yes, this
    # other origin is allowed to read this response." It needs to run
    # early enough to attach those headers to every response, including
    # ones later middleware might otherwise short-circuit
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000',
    cast=lambda v: [origin.strip() for origin in v.split(',')],
)
# The actual ALLOW-LIST — every origin (protocol + domain + port,
# EXACTLY, e.g. "https://paddy.com", not just "paddy.com") that's
# permitted to make cross-origin requests to this API and have the
# browser actually let the frontend JavaScript read the response.
# Defaults to the local Next.js dev server's default port for local
# dev. In production, this needs your REAL deployed frontend domain —
# set via .env, not hardcoded here, same reasoning as ALLOWED_HOSTS
# above: differs per environment without needing a code change
#
# Deliberately an ALLOW-LIST, never CORS_ALLOW_ALL_ORIGINS=True — that
# setting exists in django-cors-headers but would let ANY website on
# the internet read responses from this API on behalf of a logged-in
# user's browser, which defeats the entire purpose of CORS as a
# security boundary. An API serving real user data (subscriptions,
# viewing requests, contact info) should never use it

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
# NEW — this is the actual filesystem folder collectstatic will copy
# everything into. BASE_DIR is already defined at the top of settings.py
# (it's your project root), so this creates a folder called
# "staticfiles" right alongside manage.py

# STATIC_URL = where browsers ask for static files (a URL)
# STATIC_ROOT = where Django actually stores them on disk (a folder path)
# Two different things, easy to conflate since they're both "static"-named


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Cloudflare R2 (media file storage) ---
# R2 is Cloudflare's S3-compatible object storage — "S3-compatible"
# means it speaks the exact same API as Amazon S3, so we can use
# Amazon's own official tooling (boto3) and Django's own S3 storage
# backend (django-storages) to talk to R2 instead, just by pointing
# them at a different endpoint URL. Nothing else about how Django
# handles file uploads changes — ImageField/FileField on your models
# work exactly the same either way

R2_ACCESS_KEY_ID = config('R2_STORAGE_ACCESS_KEY_ID')
R2_SECRET_ACCESS_KEY = config('R2_STORAGE_SECRET_ACCESS_KEY')
R2_BUCKET_NAME = config('R2_STORAGE_BUCKET_NAME')
R2_ACCOUNT_ID = config('R2_STORAGE_ACCOUNT_ID')
# Pulled from .env via decouple, same pattern as PAYSTACK_SECRET_KEY —
# these are real credentials, never hardcoded, never committed to git


AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
# django-storages' S3 backend expects these EXACT setting names
# (AWS_...) even though we're pointing it at Cloudflare, not Amazon —
# the backend is generically written for "any S3-compatible service",
# it just happens to default its naming to AWS's own terms. We copy
# our R2 values into these AWS-named settings rather than renaming
# our own — this way it's still obvious in code review that these are
# actually R2 credentials, not real AWS ones

AWS_S3_ENDPOINT_URL = f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com'
# THE setting that actually redirects all this "AWS" configuration to
# Cloudflare's servers instead of Amazon's. Without this, django-storages
# would default to talking to real AWS S3, using YOUR R2 credentials,
# which would just fail (R2 keys don't work against real AWS)
AWS_S3_REGION_NAME = 'auto'
# R2 doesn't use AWS's real region system (us-east-1, eu-west-2, etc.)
# — 'auto' is R2's own documented placeholder value for this field,
# since the S3-compatibility layer still expects SOMETHING here
AWS_S3_ADDRESSING_STYLE = 'virtual'
# Tells boto3 to build URLs as https://bucket.endpoint/key rather than
# https://endpoint/bucket/key — R2's documented requirement, some
# S3-compatible services differ on this
AWS_S3_FILE_OVERWRITE = False
# If a new upload happens to generate the exact same filename as an
# existing file (e.g. two different landlords each upload something
# named "photo.jpg"), this tells django-storages to save the new one
# under a slightly modified name instead of silently overwriting the
# old one. Genuinely important for shared object storage — the local
# filesystem never had this collision risk in the same way, since each
# listing's photos were already namespaced by Django's own upload_to
# folder structure, but it's a free, zero-cost safety net to have
AWS_DEFAULT_ACL = 'public-read'
# Every uploaded file becomes readable via a plain public URL, with no
# authentication required to VIEW it. This matches how your app
# actually uses these files today — listing photos are shown to
# anyone browsing Discovery Hub, logged in or not, so there's no
# access-control reason to keep them private. (Genuinely different
# question from the address/contact-info paywall we built earlier —
# that's about DATA in the API response, this is about whether a
# photo FILE is fetchable if you already have its direct URL)
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        # Every uploaded file (listing photos, via ImageField) now goes
        # to R2 instead of local disk — this is the actual switch.
        # Nothing in listings/models.py needs to change at all; Django
        # doesn't know or care which storage backend is behind
        # ImageField, that's the whole point of Django's storage
        # abstraction
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        # CSS/JS/admin assets — completely separate from user-uploaded
        # media, still served by WhiteNoise/gunicorn as before. R2 is
        # ONLY for the 'default' (media) storage above
    },
}

AWS_QUERYSTRING_AUTH = False
# Without this, django-storages appends a temporary, EXPIRING signed
# token to every file URL it generates (e.g. "?X-Amz-Signature=...") —
# correct behavior for a PRIVATE bucket, where you want URLs that stop
# working after a while. Our bucket is public-read (see
# AWS_DEFAULT_ACL above), so we want plain, permanent URLs instead —
# without this setting, listing photo URLs would silently start
# returning 403 Forbidden once their embedded signature expired,
# even though the file itself is still there and still public

AWS_S3_CUSTOM_DOMAIN = 'pub-f2e74abdc1df4d9ebff24e2e0998446f.r2.dev'
# THE actual public-facing domain django-storages will use to build
# every file URL — completely SEPARATE from AWS_S3_ENDPOINT_URL above.
# AWS_S3_ENDPOINT_URL is the PRIVATE API endpoint used for authenticated
# operations (uploading, deleting) — it requires your R2 credentials to
# use. This custom domain is the PUBLIC one, freely readable by anyone
# with the URL, no credentials needed — this is what actually gets
# embedded in API responses for the frontend to load images from.
# NOTE: Cloudflare calls this a "Public Development URL" deliberately —
# it's rate-limited and has no uptime guarantee, meant for testing only.
# Before a real production launch, replace this with a proper custom
# domain (e.g. media.paddy.com) connected via R2's "Custom Domains"
# settings tab instead