"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

import os

if os.name == 'nt':
    OSGEO4W = r'C:\Users\g\AppData\Local\Programs\OSGeo4W'
    os.environ['OSGEO4W_ROOT'] = OSGEO4W
    os.environ['GDAL_DATA'] = OSGEO4W + r'\share\gdal'
    os.environ['PROJ_LIB'] = OSGEO4W + r'\share\proj'
    os.environ['PATH'] = OSGEO4W + r'\bin;' + os.environ['PATH']

    GDAL_LIBRARY_PATH = OSGEO4W + r'\bin\gdal313.dll'
    GEOS_LIBRARY_PATH = OSGEO4W + r'\bin\geos_c.dll'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
# cast=bool — WITHOUT this, config('DEBUG', ...) reads .env as a plain
# TEXT string. A classic python-decouple trap: even the string "False"
# is TRUTHY in Python (any non-empty string is truthy), so DEBUG='False'
# in .env would actually evaluate to True at runtime — the opposite of
# what it says. cast=bool tells decouple to specifically recognize the
# text "True"/"False" (case-insensitively) and convert it to a REAL
# Python boolean, avoiding that trap entirely

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [h.strip() for h in v.split(',')])
# Reads a comma-separated list from .env (e.g.
# "api.paddy.com,paddy-backend.up.railway.app") and splits it into the
# list Django actually expects. Defaults to localhost-only for local
# dev. The wildcard '*' that was here before is a genuine security risk
# in production — it accepts a request claiming ANY hostname at all,
# which is the classic ingredient for Host-header-based attacks (e.g.
# a maliciously crafted password-reset link pointing at an attacker's
# domain, if any code ever builds a URL from request.get_host()).
# Real deployed domains go in .env, not hardcoded here, so they can
# differ between environments (local/staging/production) without a
# code change


# Application definition

INSTALLED_APPS = [
    'unfold',
    'anymail',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'accounts',
    'listings',
    'viewings',
    'payments',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.gis'
]

REST_FRAMEWORK = {
    # Global DRF settings — a dict DRF looks for by this exact name

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Tells DRF: on every incoming request, check for a JWT in the
    # Authorization header, and if valid, treat it as identifying the user.
    # Without this, DRF wouldn't know JWTs exist at all — SimpleJWT is
    # installed, but not yet "plugged in" as the actual auth method

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    # Applied to EVERY view by default, unless a specific view overrides
    # throttle_classes itself. AnonRateThrottle tracks by IP address (for
    # requests with no logged-in user), UserRateThrottle tracks by user
    # ID (once authenticated) — different buckets, so a logged-in user
    # isn't sharing their rate limit with anonymous traffic from the
    # same IP (e.g. behind a shared office/mobile network NAT)

    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '120/min',
        # Baseline limits for ordinary browsing/API use — generous
        # enough that a real user scrolling Discovery Hub or a
        # landlord managing listings never notices them

        'login': '5/min',
        'register': '5/min',
        # Deliberately MUCH stricter — these are the exact endpoints a
        # brute-force/credential-stuffing attack or a spam-signup bot
        # would hammer. 5/min per IP makes that kind of automated abuse
        # genuinely slow and impractical, while still being generous
        # enough that a real person mistyping their password twice
        # never gets blocked

        'sensitive': '10/min',
        # For verify-email and similar token-based flows — not as
        # tightly limited as login/register (a real user might
        # reasonably retry a broken verification link), but still
        # meaningfully throttled against abuse

        'payments': '10/min',
        # initiate_subscription proxies to Paystack's API — throttling
        # this protects against a bug or malicious client hammering
        # OUR server into hammering Paystack's, which could trigger
        # Paystack's own abuse detection against our account

        'webhook': '100/min',
        # Deliberately generous — this endpoint's real protection is the
        # HMAC signature check, not this limit. A tight limit here risks
        # dropping GENUINE Paystack webhooks if several landlords pay
        # around the same time (Paystack could send a burst of calls).
        # This exists only to cap how much CPU a flood of garbage,
        # unsigned requests can cost us, not to gate real traffic

        'viewing_request': '10/min',
        # Applied ONLY to creating a new viewing request (see
        # ViewingViewSet.get_throttles below) — this is specifically the
        # "renter spamming viewing requests" abuse case: without this, a
        # malicious or buggy client could flood a landlord's inbox with
        # bogus viewing bookings (each one triggers a real confirmation
        # email too, so this also protects against burning through email
        # sending quota). Listing/retrieving/staff actions on viewings
        # are NOT scoped this tightly — they just fall back to the
        # global 'user' rate (120/min), since browsing your own
        # viewings isn't the same abuse risk as creating new ones
    },
}


AUTH_USER_MODEL = 'accounts.User'

EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
ANYMAIL = {
    "RESEND_API_KEY": config("RESEND_API_KEY"),
    # config(...) — same decouple pattern as PAYSTACK_SECRET_KEY/
    # GOOGLE_CLIENT_ID, reads from .env correctly. The previous
    # os.environ.get(...) silently returned None here, since
    # os.environ only sees REAL OS/shell env vars — python-decouple's
    # .env-file loading is a separate mechanism that os.environ.get()
    # never taps into on its own
}
DEFAULT_FROM_EMAIL = "hello@thegeneralyst.com"
# Local dev only — prints the email content to your terminal instead of
# actually sending it. We'll swap this for a real email service
# (e.g. SendGrid, AWS SES) once we're closer to production

MEDIA_URL = 'media/'

PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
# config(...) — same decouple pattern as GOOGLE_CLIENT_ID, reads the
# real key out of .env, never hardcoded here. This is the KEY every
# payments/views.py Paystack API call will authenticate with — same
# "one central setting" idea as EMAIL_BACKEND, just for Paystack instead

PAYSTACK_PLAN_CODE = config('PAYSTACK_PLAN_CODE', default='')
# LEGACY — superseded by the two tier-specific codes below once 3-tier
# pricing was decided. Left in place for now rather than removed, in
# case anything still references it; safe to delete once confirmed unused

PAYSTACK_AGENT_PLAN_CODE = config('PAYSTACK_AGENT_PLAN_CODE', default='')
PAYSTACK_LORD_PLAN_CODE = config('PAYSTACK_LORD_PLAN_CODE', default='')
# One real Paystack Plan per PAID tier (GHS 250/mo and GHS 1,000/mo
# respectively, created via a one-off API call, not through the
# dashboard — Paystack's dashboard doesn't have an obvious standalone
# "Plans" page, it's buried under Payment Pages). The FREE tier
# deliberately has no plan code at all — no Paystack interaction
# happens for a landlord who never exceeds their free listing
MEDIA_ROOT = BASE_DIR / 'media'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # WhiteNoise — serves static files (CSS/JS/admin assets) directly
    # from gunicorn itself in production, compressed and cache-busted,
    # without needing a separate nginx/CDN setup just to get started.
    # MUST sit directly after SecurityMiddleware (WhiteNoise's own docs
    # specify this exact position) and BEFORE anything else — it needs
    # to intercept static file requests early, before session/auth
    # middleware does unrelated work on a request that's just asking
    # for a CSS file
    'corsheaders.middleware.CorsMiddleware',
    # Must come BEFORE CommonMiddleware (django-cors-headers' own docs
    # require this exact ordering) — CORS is fundamentally about
    # deciding whether to add specific response HEADERS
    # (Access-Control-Allow-Origin, etc.) telling the BROWSER "yes, this
    # other origin is allowed to read this response." It needs to run
    # early enough to attach those headers to every response, including
    # ones later middleware might otherwise short-circuit
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000',
    cast=lambda v: [origin.strip() for origin in v.split(',')],
)
# The actual ALLOW-LIST — every origin (protocol + domain + port,
# EXACTLY, e.g. "https://paddy.com", not just "paddy.com") that's
# permitted to make cross-origin requests to this API and have the
# browser actually let the frontend JavaScript read the response.
# Defaults to the local Next.js dev server's default port for local
# dev. In production, this needs your REAL deployed frontend domain —
# set via .env, not hardcoded here, same reasoning as ALLOWED_HOSTS
# above: differs per environment without needing a code change
#
# Deliberately an ALLOW-LIST, never CORS_ALLOW_ALL_ORIGINS=True — that
# setting exists in django-cors-headers but would let ANY website on
# the internet read responses from this API on behalf of a logged-in
# user's browser, which defeats the entire purpose of CORS as a
# security boundary. An API serving real user data (subscriptions,
# viewing requests, contact info) should never use it

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
# NEW — this is the actual filesystem folder collectstatic will copy
# everything into. BASE_DIR is already defined at the top of settings.py
# (it's your project root), so this creates a folder called
# "staticfiles" right alongside manage.py

# STATIC_URL = where browsers ask for static files (a URL)
# STATIC_ROOT = where Django actually stores them on disk (a folder path)
# Two different things, easy to conflate since they're both "static"-named

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        # Tells WhiteNoise to (1) gzip/brotli-compress every static
        # file once at deploy time (via `manage.py collectstatic`),
        # rather than compressing on every single request, and (2)
        # rename each file with a content hash in its filename (e.g.
        # styles.a3f9c2.css) — this is what makes it SAFE to set a
        # far-future cache header on static files: if the file's
        # content ever changes, its hashed filename changes too, so
        # browsers never serve a stale cached version by mistake
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
