# Generated by Django 5.2.17 on 2026-09-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_landlordprofile_paystack_subaccount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('past_due', 'Past Due')], default='inactive', max_length=10)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.landlordprofile')),
            ],
        ),
    ]
