# Generated by Django 5.2.17 on 2026-09-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordsubscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('agent', 'paddy agent'), ('lord', 'paddy lord')], default='free', max_length=10),
        ),
    ]
