# Generated by Django 5.2.17 on 2026-09-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_listingunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='last_plan_charge_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='past_due_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='paystack_email_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='superseded_email_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='superseded_subscription_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
