# Generated by Django 5.2.17 on 2026-09-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_remove_landlordprofile_momo_number_and_more'),
        ('listings', '0006_remove_listing_has_backup_power_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_rent_period', models.CharField(choices=[('none', 'None'), ('6_months', '6 Months'), ('1_year', '1 Year')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases_created', to=settings.AUTH_USER_MODEL)),
                ('landlord_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='accounts.landlordprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='listings.listing')),
                ('renter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='accounts.renterprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('contract', 'Contract'), ('receipt', 'Receipt')], max_length=20)),
                ('method', models.CharField(blank=True, choices=[('momo', 'Mobile Money'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_records_created', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='leases.lease')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
