# Generated by Django 5.2.17 on 2026-09-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Awaiting renter confirmation"),
                    ("active", "Active"),
                    ("declined", "Declined by renter"),
                    ("ended", "Ended"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
