# Generated by Django 5.2.17 on 2026-09-11 00:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_oauth_data_user_sign_in_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='rent', max_length=10)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_one_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance_rent_period', models.CharField(blank=True, choices=[('none', 'None'), ('6_months', '6 Months'), ('1_year', '1 Year')], max_length=10, null=True)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('has_water_storage', models.BooleanField(default=False)),
                ('has_backup_power', models.BooleanField(default=False)),
                ('is_walled_gated', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('address_precise', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.landlordprofile')),
                ('verified_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_listings', to='accounts.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
