# Generated by Django 5.2.17 on 2026-09-15 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('water_storage', 'Water Storage'), ('backup_power', 'Backup Power'), ('walled_gated', 'Walled Gated'), ('wifi', 'Wifi'), ('parking', 'Parking'), ('gym', 'Gym'), ('swimming_pool', 'Swimming Pool'), ('furnished', 'Furnished'), ('air_conditioning', 'Air Conditioning'), ('security', 'Security'), ('maintenance', 'Maintenance')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
