# Generated by Django 5.2.17 on 2026-09-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('listings', '0005_listing_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='has_backup_power',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='has_water_storage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_walled_gated',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='amenities',
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='listings', to='core.amenity'),
        ),
    ]
