# Generated by Django 5.2.17 on 2026-09-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_landlordprofile_momo_number_and_more'),
        ('listings', '0006_remove_listing_has_backup_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('renter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to='accounts.renterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('renter_profile', 'listing')},
            },
        ),
    ]
