# Generated by Django 5.2.17 on 2026-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_backfill_listing_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
