# Generated by Django 5.2.17 on 2026-09-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_slug_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('leased', 'Leased'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
    ]
