# Generated by Django 5.2.17 on 2026-10-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_status_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
